export const PROJECTS = [
    {
        img: '/images/FoodRecipe.jpeg',
        tag: 'HTML • CSS • JavaScript • Netlify',
        title: 'Food Recipes by Ahmad',
        desc: 'A dynamic recipe discovery app powered by The MealDB API — search thousands of dishes worldwide.',
        link: 'https://food-recipe-app-by-ahmad.netlify.app',
        github: 'https://github.com/AhmadMughal-web/Food-Recipe-App.git',
        cat: 'frontend', featured: true, coming: false,
    },
    {
        img: '/images/Agency.ai.jpeg',
        tag: 'React • Tailwind • Netlify',
        title: 'AI Agency Landing',
        desc: 'An AI-based agency landing page built with React & Tailwind. Fully responsive with interactive components.',
        link: 'https://shiny-begonia-42fbfe.netlify.app',
        github: 'https://github.com/AhmadMughal-web/Agency.AI.git',
        cat: 'frontend', featured: true, coming: false,
    },
    {
        img: '/images/Awwwards.jpeg',
        tag: 'React • Animations • Video • Netlify',
        title: 'Gaming Trailer Website',
        desc: 'An immersive gaming trailer website built with React — featuring video integration, smooth animations and cinematic UI.',
        link: 'https://soft-belekoy-cc58c4.netlify.app',
        github: 'https://github.com/AhmadMughal-web/awwwards-website.git',
        cat: 'frontend', featured: true, coming: false,
    },
    {
        img: '/images/alghani.png',
        tag: 'React • Responsive • Bilingual • Netlify',
        title: 'Unani Herbal Healthcare Platform — Al Ghani',
        desc: 'Unani & Herbal medicine website built for a real client — featuring bilingual EN/UR language toggle,  consultation form, and a stunning herbal UI.',
        link: 'https://al-ghani.netlify.app',
        github: 'https://github.com/AhmadMughal-web/Al-Ghani.git',
        cat: 'frontend', featured: true, coming: false,
    },
    {
        img: '/images/nexus.png',
        tag: 'React • Node.js • Groq API • MongoDB • Netlify • Render',
        title: 'NexusAI — Career Intelligence Platform',
        desc: 'A full-stack AI agent built with React & Node.js — featuring real-time AI chat, JWT auth, PDF export and MongoDB integration.',
        link: 'https://nexusai-2026.netlify.app',
        github: 'https://github.com/AhmadMughal-web/nexusai.git',
        cat: 'ai', featured: true, coming: false,
    },
    {
        img: '/images/Portfolio.png',
        tag: 'React • Node.js • Groq API • MongoDB • Netlify • Render',
        title: 'Portfolio — Career Intelligence Platform',
        desc: 'A full-stack AI agent built with React & Node.js — featuring real-time AI chat, JWT auth, PDF export and MongoDB integration.',
        link: 'https://nexusai-2026.netlify.app',
        github: 'https://github.com/AhmadMughal-web/nexusai.git',
        cat: 'ai', featured: true, coming: false,
    },
    {
        img: '/images/pingup.png',
        tag: 'React •Tailwind • Node.js • MongoDB • Netlify • Render',
        title: 'PingUp — Social Media Platform',
        desc: 'A full-stack social media platform built with React & Node.js — featuring real-time messaging, user authentication, and MongoDB integration.',
        link: 'https://pingup-social-media-platform.netlify.app',
        github: 'https://github.com/AhmadMughal-web/PingUp.git',
        featured: true,
        coming: false, cat: 'fullstack'
    },
    {
        img: '/images/ECommerce.png',
        tag: 'React •Tailwind • Node.js • MongoDB • Netlify • Render',
        title: 'E-Commerce Platform',
        desc: 'A full-stack E-Commerce platform.  — Where you can sell and buy differentf products, with real-time chat support and secure authentication.',
        link: 'https://e-shop1-website.netlify.app',
        github: 'https://github.com/AhmadMughal-web/ECommerce-Website.git',
        featured: true,
        coming: false, cat: 'fullstack'
    },
    {
        img: '',
        tag: 'React • Node • MongoDB',
        title: 'Full Stack App',
        desc: 'A full-stack web application in progress — REST API backend, MongoDB database, and modern React frontend.',
        link: '#',
        github: '',
        cat: 'coming', featured: false, coming: true,
    },
];
